config/routes.rb
RadioCmf::Application.routes.draw do
  get "admin/admin" ,:as => "admin"
  get "contacto/contacto" ,:as => "contactanos"
  get "programacion/programacion" ,:as => "programacion"
  get "qsomos/qsomos" ,:as => "somos"
  get "home/index"

   root 'home#index'

  

end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  def admin
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/contacto_controller.rb
class ContactoController < ApplicationController
  def contacto
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/programacion_controller.rb
class ProgramacionController < ApplicationController
  def programacion
  end
end

app/controllers/qsomos_controller.rb
class QsomosController < ApplicationController
  def qsomos
  end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacto_helper.rb
module ContactoHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/programacion_helper.rb
module ProgramacionHelper
end

app/helpers/qsomos_helper.rb
module QsomosHelper
end

app/views/admin/admin.html.erb
<h1>Admin#admin</h1>
<p>Find me in app/views/admin/admin.html.erb</p>

app/views/contacto/contacto.html.erb
<h1>Contacto#contacto</h1>
<p>Find me in app/views/contacto/contacto.html.erb</p>

app/views/home/_programas.html.erb
 <!-- rows of services -->
            <div  id = "home" class="row services-desc">
				
				<article class="row-fluid">

                <h4>Todos nuestros Programas Radiales</h4>

                <div class="span6">
                    <%= image_tag("soplandovida.png" , size:"260x400") %>             
                    <h5>Soplando vida, "Reflexion del dia"</h5>
                    <span class="services-desc">
                       This is Photoshop's version  of Lorem Ipsum. Proin gravida nibh vel velit auctor aliquet.<br><br>Aenean sollicitudin, lorem quis bibendum auctor, nisi elit consequat ipsum, nec sagittis sem nibh id elit. Duis sed odio sit amet nibh vulputate cursus a sit amet mauris. 
                    </span>
                </div>
                <div class="span5">
                   
                    <%= image_tag("gravedadcero.png" , size:"260x400") %>
                    <h5>  <br> Maquetación</h5>
                    <span>
						
						
                        This is Photoshop's version  of Lorem Ipsum. Proin gravida nibh vel velit auctor aliquet. Aenean sollicitudin, lorem quis bibendum auctor, nisi elit consequat ipsum, nec sagittis.<br><br>Sem nibh id elit. Duis sed odio sit amet nibh vulputate cursus a sit amet mauris.  
                    </span>
                </div>
                
                </article>
          
                
            </div>

            <!-- rows of Secial Proyect -->
            
            <div id="home" class="row special-proy">
                
                <div class="span12">
                    <h4>Quiere comentar?</h4>            
                   <span>
                    This is Photoshop's version  of Lorem Ipsum. Proin gravida nibh vel velit auctor aliquet.
                         Aenean sollicitudin, lorem quis bibendum auctor, nisi elit consequat ipsum, nec sagittis 
                         sem nibh id elit. <br><br>
                         Duis sed odio sit amet nibh vulputate cursus a sit amet mauris. Morbi
                          accumsan ipsum velit. Nam nec tellus a odio tincidunt auctor a ornare odio.    
                   </span>   
                    <div class="cont-read"><i class="icon icon-arrow-blue"></i> continuar leyendo  <br> <br> </div>
                </div>
                <div>
					
                <!-- BEGIN CBOX - www.cbox.ws - v001 -->
				<div id="cboxdiv" style="text-align: center; line-height: 0">
					<div><iframe frameborder="0" width="550" height="300" 
					src="http://www5.cbox.ws/box/?boxid=830319&amp;boxtag=5w5tbq&amp;sec=main" 
					marginheight="2" marginwidth="2" scrolling="auto" allowtransparency="yes" 
					name="cboxmain5-830319" style="border:#48515A 1px solid;" id="cboxmain5-830319">
					</iframe></div>
				<div><iframe frameborder="0" width="550" height="75" 
				src="http://www5.cbox.ws/box/?boxid=830319&amp;boxtag=5w5tbq&amp;sec=form" 
				marginheight="2" marginwidth="2" scrolling="no" allowtransparency="yes" 
				name="cboxform5-830319" style="border:#48515A 1px solid;border-top:0px" 
				id="cboxform5-830319"></iframe></div>
				</div>
				<!-- END CBOX -->
                
                </div>
                
            </div>
        
            <!-- rows of videos -->
            <div id="home"class="row videos-desc">

                <h4>Tus proyectos son nuestra prioridad</h4>

                <div class="span3">
                    <a href="#myModal-1" role="button" data-toggle="modal"><img src="img/video1.png"></a>
                    <h6>Nuestros diseños son nuestra carta de presentación</h6>                    
                </div>
                <div class="span3">
                    <a href="#myModal-2" role="button" data-toggle="modal"><img src="img/video2.png"></a>
                    <h6>Buscar la inspiración para cada proyecto es fundamental.</h6>
                </div>
                <div class="span3">
                    <a href="#myModal-3" role="button" data-toggle="modal"><img src="img/video3.png"></a>
                    <h6>Tener clientes satisfechos es una de nuestras prioridades.</h6>                    
                </div>
                <div class="span2">
                    <a href="#myModal-4" role="button" data-toggle="modal"><img src="img/video4.png"></a>
                    <h6>Ponemos a tu disposicion toda nuestra experiencia y equipo.</h6>
                </div>
            </div>

app/views/home/index.html.erb
<section id = "home">
	
		
	
		<article id="historia">
			<h3>Bienvenidos a  Radio Cristomorfosis</h3>
			
			<p> Este Programa Radial tiende el agrado de Saludarlos y darles la Bienvenida 
			a nuestro sitio Web, donde compartiremos el mensaje de Dios  a sus vidas, también 
			alabanzas y pedidos musicales. Todos los Viernes a partir de las 10:00 hrs. de la 
			noche Dios los bendiga Amables Oyentes.  Att. Los jóvenes de la Familia Cristomorfosis </p>
		</article>
		
</section>

<section>
  <%= render 'programas' %>
</section>

 

app/views/layouts/_navigation.html.erb
<!-- <div class="brand"><i class="icon-home"></i></div> -->
<%= link_to "Cristomorfosis", root_path, :class => 'brand'%>
<ul id= "nav"  class="nav pull-right" >
  <li><%= link_to "Quiénes Somos" ,somos_path  %></li>
  <li><%= link_to "Programacion",programacion_path %></li>
  <li><%= link_to "Contactanos" ,contactanos_path%></li>
  <li>		
	<form class="navbar-search" action="/artists/search">
		<input class="search-query input-medium" type="text" name="q" placeholder="buscar">
			<i class="icon-search icon-white"></i>
		</input>
	</form>
  </li>
  <li class="divider-vertical"></li>	
 
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Radio Cristomorfosis" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Hackday" %>">
    <%= stylesheet_link_tag "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <%= yield(:head) %>
</head>



<body class="<%= controller_name %> <%= action_name %>">




	  <div    class="navbar navbar-fixed-top navbar-inverse">
      <nav class="navbar-inner">
        <div class="container">
           
        </div>
      </nav>
    </div>




    <div id= "menu-principal" class="navbar navbar-fixed-top navbar-inverse">
      <nav class="navbar-inner">
        <div class="container">
            <!-- reder layout navigation -->
            <%= render 'layouts/navigation' %>
        </div>
      </nav>
    </div>
    
    <header >
		
		
   <!--     <div  class="row-fluid">	
        <div class="span2"></div>
			<div id= "imagen_portada" class="span8"><%= image_tag("logo-fondo.png", size:"500x600") %></div>
			<!-- <div class="span8 titulo">
				<h1>Radio Cristomorfosis</h1>
				<h4>"Mas que musica, un momento de reflexion"</h4>						
			</div> -->
           <!-- <div class="span10"><%= image_tag("logo_3.png", size:"450x1200" ) %></div> -->
           
           <div class="span2"></div>
		</div> -->
		
		
		
		
		
		<div class="banner">
            <div id="myCarousel" class="carousel slide banner-container">
                <ol class="carousel-indicators">
                    <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
                    <li data-target="#myCarousel" data-slide-to="1"></li>
                    <li data-target="#myCarousel" data-slide-to="2"></li>
                </ol>

                <!-- Carousel items -->
                <div class="carousel-inner">
                    <div class="active item"><%= image_tag("logo-fondo.png", size:"300x600") %></div>
                    <div class="item"><%= image_tag("logo-soplandovida.png", size:"500x600") %></div>
                    <div class="item"><%= image_tag("logo-gravedadcero.png", size:"500x600") %></div>
                </div>

                <!-- Carousel nav -->
                <a class="control left" href="#myCarousel" data-slide="prev"><%= image_tag("left.jpg") %></a>
                <a class="control right" href="#myCarousel" data-slide="next"><%= image_tag("right.jpg") %></a>
            </div>
        </div>
		
		
		
	
		
	</header>
	
	
	
	
    <div id="main" role="main">
      <div class="container"> 
        <div class="content">
			<div class="row-fluid">

                <section id="menu-izq">
                    <div class="span2">
                        <div class="well sidebar-nav">
                            <ul class="nav nav-list">
								 <li class="nav-header">MENU</li>
								 <li class="active"><%= link_to "Inicio" %></li>
                                <li><%= link_to "Encuestas" %></li>
                                <li><%= link_to "Quienes somos" %></li>
                                <li><%= link_to "Descargas" %></li>
                                <li><%= link_to "Videos" %></li>
                                
                                <li class="nav-header">PROGRAMACION</li>                  
              
                                <li><%= link_to "Graveda Cero"%></li>
                                <li><%= link_to "La hora Pepito" %></li>
                                <li><%= link_to "Soplando Vida" %></li>
                                <li><%= link_to "En Familia" %></li>
                                <li class="nav-header">REFLEXIONES</li>
                                <li><%= link_to "Amor" %></li>
                                <li><%= link_to "Economicos" %></li>
                                <li><%= link_to "Familias" %></li>
                                <li><%= link_to "Noviazgo" %></li>
                                <li><%= link_to "Deprecion" %></li>
                                <li class="nav-header">AUSPICIADORES</li>
                                <li><%= link_to "Basadrinux" %></li>
                                <li><%= link_to "Basadre.net" %></li>
                            </ul>
                        </div>
                    </div>
                </section>
                
                <section >
                    <div  id="contenido_central" class="span8 ">
						<div>
						<header id="cabecera" > <h6>titulo del contenido</h6></header>
						</div>
                       <!-- <= render 'layouts/messages' %> -->
                        <%= yield %>
                    </div> 
                </section>
                
                <section >
                    <div  class="span2">
						
						<div id="menu-der">
						  <h4>Escuchanos</h4> 
						  <object width="240" height="300"><param name="allowscriptaccess" value="always" /><param name="movie" value="http://static.radionomy.com/cdn/flash/BannerEmbed.swf?RadUID=b6f41e6b-2598-4dea-9eb5-4974463d56e3&amp;titlesColor=ffffff&amp;color=7d7d7d&amp;autoPlay=yes&amp;lang=en" /><param name="wmode" value="transparent" /><embed src="http://static.radionomy.com/cdn/flash/BannerEmbed.swf?RadUID=b6f41e6b-2598-4dea-9eb5-4974463d56e3&amp;titlesColor=ffffff&amp;color=7d7d7d&amp;autoPlay=yes&amp;lang=en" wmode="transparent" type="application/x-shockwave-flash" allowscriptaccess="always" width="155" height="200"></embed></object>
                       
                       
                       <span>Estas escuchando Radio Cristomrofosis</span>
                       
						</div>
						
						<div id="noticias">
						
						 <h4>Noticias</h4>
						
						</div>
                     
                       
                       
                   
                       
                       
                       
                    </div>
                </section>
                
                

          </div>
          
        </div>
      </div> <!--! end of .container -->
    </div> <!--! end of #main -->
    
    
    
    <footer>
		<div class="row-fluid">	
			
			  <div class="span3"></div>
			 <div class="span5">
			<h5>Contactenos</h5>
			<p>Empresa Sheep developer - Ciudad Nueva - Av. Internacional - Central Telefónica: 052 311483</p>	
		  
			<p>Tacna - PERÚ</p> 
			</div>
			 <div class="span1"><%= image_tag("logo.png", size:"55x130" ) %></div>
			 <div class="span3"></div>
			
        </div>
    </footer>



</body>

</html>

app/views/programacion/programacion.html.erb
<h1>Programacion#programacion</h1>
<p>Find me in app/views/programacion/programacion.html.erb</p>

app/views/qsomos/qsomos.html.erb
<h1>Qsomos#qsomos</h1>
<p>Find me in app/views/qsomos/qsomos.html.erb</p>